import { tr } from "./helpers";

export default {
  guidanceUnavailable: tr("Base44 guidance is unavailable — showing a labeled sample result.", "La guía de Base44 no está disponible; se muestra un resultado de muestra etiquetado.", "Ndigalu Base44 jëfekoo tu — misaal bu am màndarga lañuy wone.", "إرشاد Base44 غير متاح — يتم عرض نتيجة عينة موسومة.", "Base44 নির্দেশনা অনুপলভ্য — লেবেলযুক্ত নমুনা ফল দেখানো হচ্ছে।", "Base44 指引不可用—正在显示有明确标签的样本结果。", "Le guidage Base44 est indisponible — un résultat exemple étiqueté est affiché."),
  liveSpeechUnavailable: tr("Live speech is unavailable for this locale or device. Type your question or use the labeled sample.", "La voz en vivo no está disponible para este idioma o dispositivo. Escribe tu pregunta o usa la muestra etiquetada.", "Baat ci jamono jëfekoo tu ci làkk walla jumtukaay bii. Bindal sa laaj walla jëfandikoo misaal bi.", "الصوت المباشر غير متاح لهذه اللغة أو على هذا الجهاز. اكتب سؤالك أو استخدم العينة الموسومة.", "এই ভাষা বা ডিভাইসে লাইভ স্পিচ অনুপলভ্য। প্রশ্ন লিখুন বা লেবেলযুক্ত নমুনা ব্যবহার করুন।", "此语言或设备不支持实时语音。请键入问题或使用标记清楚的样本。", "La parole en direct est indisponible pour cette langue ou cet appareil. Tapez votre question ou utilisez l’exemple étiqueté."),
  speechFailed: tr("Speech could not be read. Nothing was guessed; use typed input or the sample.", "No se pudo leer la voz. No se adivinó nada; usa texto o la muestra.", "Manuñu jàng baat bi. Ñu xalaatul dara; bindal walla jëfandikoo misaal bi.", "تعذرت قراءة الصوت. لم يتم تخمين شيء؛ استخدم الكتابة أو العينة.", "কথা পড়া যায়নি। কিছু অনুমান করা হয়নি; লিখে দিন বা নমুনা ব্যবহার করুন।", "无法识别语音。系统未作猜测；请键入或使用样本。", "La parole n’a pas pu être reconnue. Rien n’a été deviné ; utilisez la saisie ou l’exemple."),
  playbackUnavailable: tr("Matching speech playback is unavailable.", "La reproducción de voz correspondiente no está disponible.", "Déglu baat bu méngoo jëfekoo tu.", "تشغيل الصوت المطابق غير متاح.", "মিলযুক্ত স্পিচ প্লেব্যাক অনুপলভ্য।", "匹配的语音播放不可用。", "La lecture vocale correspondante est indisponible."),
  fictionalImage: tr("Use a fictional image under 10 MB.", "Usa una imagen ficticia de menos de 10 MB.", "Jëfandikool nataal bu sosu bu yéesul 10 MB.", "استخدم صورة خيالية أصغر من 10 ميغابايت.", "১০ এমবি-র কম একটি কাল্পনিক ছবি ব্যবহার করুন।", "请使用小于 10 MB 的虚构图片。", "Utilisez une image fictive de moins de 10 Mo."),
  extractionUnavailable: tr("Live extraction is unavailable. No number was guessed.", "La extracción en vivo no está disponible. No se adivinó ningún número.", "Génne ci jamono jëfekoo tu. Ñu xalaatul benn nimero.", "الاستخراج المباشر غير متاح. لم يتم تخمين أي رقم.", "লাইভ এক্সট্রাকশন অনুপলভ্য। কোনো নম্বর অনুমান করা হয়নি।", "实时提取不可用。系统未猜测编号。", "L’extraction en direct est indisponible. Aucun numéro n’a été deviné."),
  publicUnavailable: tr("Public source unavailable. No conclusion was made about this notice.", "Fuente pública no disponible. No se llegó a ninguna conclusión sobre este aviso.", "Gàllu ñépp jëfekoo tu. Ñu dogaluñu dara ci bataaxal bii.", "المصدر العام غير متاح. لم يتم التوصل إلى استنتاج بشأن هذا الإشعار.", "পাবলিক উৎস অনুপলভ্য। এই নোটিশ সম্পর্কে কোনো সিদ্ধান্ত নেওয়া হয়নি।", "公共来源不可用。未对此通知作出结论。", "Source publique indisponible. Aucune conclusion n’a été tirée sur cet avis."),
  invalidAmount: tr("Enter a valid sample amount.", "Ingresa un monto de muestra válido.", "Dugalal xaalisu misaal bu baax.", "أدخل مبلغًا تجريبيًا صالحًا.", "একটি বৈধ নমুনা পরিমাণ লিখুন।", "请输入有效的样本金额。", "Saisissez un montant d’exemple valide."),
  unclearAmount: tr("The amount was unclear. Nothing was saved.", "El monto no quedó claro. No se guardó nada.", "Xaalis bi leerul. Ñu dencul dara.", "كان المبلغ غير واضح. لم يتم حفظ شيء.", "পরিমাণটি অস্পষ্ট ছিল। কিছু সংরক্ষণ করা হয়নি।", "金额不清楚。未保存任何内容。", "Le montant était incertain. Rien n’a été enregistré."),
  sayAmount: tr("Say the sale amount.", "Di el monto de la venta.", "Waxal xaalisu jaay bi.", "اذكر مبلغ البيع.", "বিক্রির পরিমাণ বলুন।", "请说出销售金额。", "Dites le montant de la vente."),
  cashSaved: tr("Self-reported sale saved.", "Venta autoinformada guardada.", "Jaay bi nga wax denc na.", "تم حفظ البيع المبلّغ عنه ذاتيًا.", "নিজে জানানো বিক্রি সংরক্ষিত হয়েছে।", "自行申报的销售已保存。", "Vente déclarée enregistrée."),
  localCash: tr("Base44 write unavailable — saved only in this visibly simulated view.", "La escritura de Base44 no está disponible; se guardó solo en esta vista simulada.", "Denc ci Base44 jëfekoo tu — ci xoolin bu ñu mel ni bii rekk la denc.", "الكتابة إلى Base44 غير متاحة — تم الحفظ في هذه الواجهة المحاكية فقط.", "Base44-তে লেখা অনুপলভ্য — শুধু দৃশ্যমান সিমুলেটেড ভিউতে সংরক্ষিত।", "Base44 写入不可用—仅保存在明确标记的模拟视图中。", "Écriture Base44 indisponible — enregistré uniquement dans cette vue simulée."),
  checkoutDone: tr("Demo checkout complete. No money moved.", "Pago de demo completado. No se movió dinero.", "Peymaanu demo jeex na. Xaalis demul fenn.", "اكتمل الدفع التجريبي. لم تُنقل أموال.", "ডেমো চেকআউট সম্পন্ন। কোনো অর্থ স্থানান্তর হয়নি।", "演示结账完成。未发生资金转移。", "Paiement de démonstration terminé. Aucun argent n’a été transféré."),
  localCheckout: tr("Backend unavailable — created only a visibly simulated local event.", "Backend no disponible; se creó solo un evento local visiblemente simulado.", "Backend jëfekoo tu — jëf bu ñu mel ni ci fii rekk la sos.", "الواجهة الخلفية غير متاحة — تم إنشاء حدث محلي محاكى بوضوح فقط.", "ব্যাকএন্ড অনুপলভ্য — শুধু দৃশ্যমান সিমুলেটেড স্থানীয় ইভেন্ট তৈরি হয়েছে।", "后端不可用—仅创建了明确标记的本地模拟事件。", "Backend indisponible — seul un événement local clairement simulé a été créé."),
  sessionUnavailable: tr("Base44 session data is unavailable — using bundled sample data.", "Los datos de sesión de Base44 no están disponibles; se usan datos de muestra incluidos.", "Done sesaan Base44 jëfekoo tu — done yu misaal yi lañuy jëfandikoo.", "بيانات جلسة Base44 غير متاحة — يتم استخدام بيانات عينة مضمّنة.", "Base44 সেশন ডেটা অনুপলভ্য — বান্ডেল করা নমুনা ডেটা ব্যবহার হচ্ছে।", "Base44 会话数据不可用—正在使用内置样本数据。", "Les données de session Base44 sont indisponibles — utilisation des données exemples intégrées."),
  newSessionSuccess: tr("New Base44 demo session created. The QR is ready.", "Nueva sesión de demo Base44 creada. El QR está listo.", "Sesaanu demo Base44 bu bees sos na. QR bi jekk na.", "تم إنشاء جلسة Base44 تجريبية جديدة. رمز QR جاهز.", "নতুন Base44 ডেমো সেশন তৈরি হয়েছে। QR প্রস্তুত।", "已创建新的 Base44 演示会话。二维码已就绪。", "Nouvelle session de démo Base44 créée. Le QR est prêt."),
  newSessionFailure: tr("A new Base44 session could not be created. The current session is unchanged.", "No se pudo crear una nueva sesión Base44. La sesión actual no cambió.", "Manuñu sos sesaan Base44 bu bees. Sesaan bii soppeekuwul.", "تعذر إنشاء جلسة Base44 جديدة. الجلسة الحالية لم تتغير.", "নতুন Base44 সেশন তৈরি করা যায়নি। বর্তমান সেশন অপরিবর্তিত।", "无法创建新的 Base44 会话。当前会话未改变。", "Impossible de créer une nouvelle session Base44. La session actuelle reste inchangée."),
  resetSuccess: tr("Rosa’s synthetic session was reset to its exact seed.", "La sesión sintética de Rosa se restableció exactamente.", "Sesaanu Rosa bu ñu sos dellu na ci njëlbeenam.", "أُعيدت جلسة روزا الاصطناعية إلى حالتها الأولية تمامًا.", "রোসার সিনথেটিক সেশন ঠিক প্রাথমিক অবস্থায় ফিরেছে।", "Rosa 的合成会话已精确重置到种子状态。", "La session synthétique de Rosa a été réinitialisée exactement."),
  resetFallback: tr("Base44 reset unavailable — only the bundled sample view was restored.", "El restablecimiento de Base44 no está disponible; solo se restauró la vista de muestra incluida.", "Reset Base44 jëfekoo tu — xoolinu misaal bi rekk lañu delloo.", "إعادة ضبط Base44 غير متاحة — تمت استعادة واجهة العينة فقط.", "Base44 রিসেট অনুপলভ্য — শুধু বান্ডেল করা নমুনা ভিউ ফিরেছে।", "Base44 重置不可用—仅恢复了内置样本视图。", "Réinitialisation Base44 indisponible — seule la vue exemple intégrée a été restaurée."),
};
