import { tr } from "./helpers";

export default {
  preliminary: tr("PRELIMINARY DEMO GUIDANCE", "GUÍA PRELIMINAR DE DEMO", "NDIGALU DEMO BU NJËKK", "إرشاد تجريبي أولي", "প্রাথমিক ডেমো নির্দেশনা", "初步演示指引", "ORIENTATION PRÉLIMINAIRE DE DÉMO"),
  listen: tr("Listen to answer", "Escuchar respuesta", "Déglu tontu bi", "استمع إلى الإجابة", "উত্তর শুনুন", "收听回答", "Écouter la réponse"),
  source: tr("View source and trace", "Ver fuente y trazabilidad", "Xool gàll ak jaar-jaaram", "عرض المصدر والتتبع", "উৎস ও ট্রেস দেখুন", "查看来源与追踪", "Voir la source et la trace"),
  rulebook: tr("Rulebook {{hash}}", "Reglamento {{hash}}", "Sàrti demo {{hash}}", "كتيب القواعد {{hash}}", "নিয়মপুস্তক {{hash}}", "规则册 {{hash}}", "Règles {{hash}}"),
  demoTrace: tr("Demo-only source trace", "Trazabilidad solo de demo", "Jaari gàll bu demo rekk", "تتبع مصدر للعرض فقط", "শুধু ডেমোর উৎস ট্রেস", "仅演示用来源追踪", "Trace de source réservée à la démo"),
  knownAnswer: tr("According to the sample checklist, one possible next step is to review the state sales-tax certificate. Confirm it with the responsible agency or a qualified service provider.", "Según la lista de muestra, un posible próximo paso es revisar el certificado estatal de impuesto sobre ventas. Confírmalo con la agencia responsable o con un proveedor de servicios calificado.", "Ni ko limu misaal bi waxe, jéego ji mën a topp mooy seetal kayitu juuti jaay bu réew mi. Dëggal ko ak kurél gi ko yore walla ab jëwriñkat bu am xam-xam.", "وفقًا للقائمة التجريبية، قد تكون الخطوة التالية مراجعة شهادة ضريبة المبيعات للولاية. أكّد ذلك مع الجهة المسؤولة أو مقدم خدمة مؤهل.", "নমুনা তালিকা অনুযায়ী, সম্ভাব্য পরবর্তী ধাপ হলো অঙ্গরাজ্যের বিক্রয় কর সনদ পর্যালোচনা করা। দায়িত্বশীল সংস্থা বা যোগ্য সেবাদাতার সঙ্গে নিশ্চিত করুন।", "根据样本清单，一个可能的下一步是查看州销售税证明。请向主管机构或合格服务提供者确认。", "Selon la liste exemple, une prochaine étape possible consiste à vérifier le certificat de taxe de vente de l’État. Confirmez-la auprès de l’agence responsable ou d’un prestataire qualifié."),
  abstainAnswer: tr("This question needs human or legal review. SIDEWALK found no sample rule that determines it.", "Esta pregunta necesita revisión humana o legal. SIDEWALK no encontró una regla de muestra que la determine.", "Laaj bii soxla na nit walla ku xam yoon mu seet ko. SIDEWALK gisul sàrtu misaal buy dogal ko.", "يحتاج هذا السؤال إلى مراجعة بشرية أو قانونية. لم يجد SIDEWALK قاعدة تجريبية تحسمه.", "এই প্রশ্নে মানবিক বা আইনি পর্যালোচনা প্রয়োজন। SIDEWALK এমন কোনো নমুনা নিয়ম পায়নি যা এটি নির্ধারণ করে।", "这个问题需要人工或法律审查。SIDEWALK 未找到可作判断的样本规则。", "Cette question nécessite un examen humain ou juridique. SIDEWALK n’a trouvé aucune règle exemple permettant d’y répondre."),
  sampleRulebook: tr("SIDEWALK sample rulebook snapshot", "Instantánea del reglamento de muestra de SIDEWALK", "Nataalu sàrti misaal yu SIDEWALK", "لقطة من كتيب قواعد SIDEWALK التجريبي", "SIDEWALK নমুনা নিয়মপুস্তকের স্ন্যাপশট", "SIDEWALK 样本规则册快照", "Extrait du recueil de règles exemple SIDEWALK"),
  noRule: tr("No matching sample rule", "No hay una regla de muestra coincidente", "Amul sàrtu misaal bu méngoo", "لا توجد قاعدة تجريبية مطابقة", "কোনো মিলযুক্ত নমুনা নিয়ম নেই", "没有匹配的样本规则", "Aucune règle exemple correspondante"),
  deviceSpeech: tr("DEVICE SPEECH", "VOZ DEL DISPOSITIVO", "BAATU JUMTUKAAY", "صوت الجهاز", "ডিভাইস স্পিচ", "设备语音", "VOIX DE L’APPAREIL"),
  sampleAudio: tr("SAMPLE AUDIO", "AUDIO DE MUESTRA", "BAATU MISAAL", "صوت تجريبي", "নমুনা অডিও", "样本音频", "AUDIO EXEMPLE"),
  speechUnavailable: tr("SPEECH UNAVAILABLE", "VOZ NO DISPONIBLE", "BAAT JËFEKOO TU", "الصوت غير متاح", "স্পিচ অনুপলভ্য", "语音不可用", "VOIX INDISPONIBLE"),
  liveAsr: tr("LIVE ASR · 8S MAX", "ASR EN VIVO · MÁX. 8 S", "ASR CI JAMONO · 8S REKK", "تعرف صوتي مباشر · 8 ثوانٍ كحد أقصى", "লাইভ ASR · সর্বোচ্চ ৮ সেকেন্ড", "实时语音识别 · 最长 8 秒", "ASR EN DIRECT · 8 S MAX"),
  fixtureFirst: tr("Fixture-first voice for this locale", "Voz de muestra primero para este idioma", "Baatu misaal moo jiitu ci làkk bii", "الصوت التجريبي أولًا لهذه اللغة", "এই ভাষায় আগে নমুনা অডিও", "此语言优先使用样本音频", "Audio exemple prioritaire pour cette langue"),
  chineseVoiceLabel: tr("Simplified Chinese · Mandarin voice", "Chino simplificado · Voz en mandarín", "Sinuwaa bu yombal · Baatu Mandarin", "الصينية المبسطة · صوت الماندرين", "সরলীকৃত চীনা · ম্যান্ডারিন কণ্ঠ", "简体中文 · 普通话语音", "Chinois simplifié · Voix mandarine"),
};
