import { tr } from "./helpers";

export default {
  before: tr("BEFORE YOU TRY SIDEWALK", "ANTES DE PROBAR SIDEWALK", "LU JIITU NGA JËFANDIKOO SIDEWALK", "قبل تجربة SIDEWALK", "SIDEWALK ব্যবহারের আগে", "试用 SIDEWALK 前", "AVANT D’ESSAYER SIDEWALK"),
  title: tr("A safe space for a fictional story.", "Un espacio seguro para una historia ficticia.", "Béréb bu wóor ngir nettali bu sosu.", "مساحة آمنة لقصة خيالية.", "একটি কাল্পনিক গল্পের জন্য নিরাপদ স্থান।", "用于虚构故事的安全空间。", "Un espace sûr pour une histoire fictive."),
  body: tr("Use only the provided demo materials. Do not enter personal, financial, immigration, or confidential information.", "Usa solo los materiales de demostración proporcionados. No ingreses información personal, financiera, migratoria ni confidencial.", "Jëfandikool rekk jumtukaayi demo yi ñu joxe. Bul dugal xibaaru bopp, xaalis, doxalin tukki walla lu nëbbu.", "استخدم مواد العرض المقدمة فقط. لا تدخل معلومات شخصية أو مالية أو متعلقة بالهجرة أو سرية.", "শুধু দেওয়া ডেমো উপকরণ ব্যবহার করুন। ব্যক্তিগত, আর্থিক, অভিবাসন বা গোপন তথ্য দেবেন না।", "仅使用提供的演示材料。请勿输入个人、财务、移民或机密信息。", "Utilisez uniquement les éléments de démonstration fournis. Ne saisissez aucune donnée personnelle, financière, migratoire ou confidentielle."),
  fictionalPoint: tr("Rosa and every case are fictional", "Rosa y todos los casos son ficticios", "Rosa ak mbir yépp dañu leen sos", "روزا وجميع الحالات خيالية", "রোসা ও সব কেস কাল্পনিক", "Rosa 和所有案例均为虚构", "Rosa et tous les dossiers sont fictifs"),
  noSideEffectsPoint: tr("No money, filings, or messages leave this demo", "Ningún dinero, trámite ni mensaje sale de esta demo", "Xaalis, dencal walla bataaxal du génn ci demo bi", "لا تغادر أي أموال أو إيداعات أو رسائل هذا العرض", "এই ডেমো থেকে কোনো টাকা, দাখিল বা বার্তা বাইরে যায় না", "本演示不会转出资金、提交文件或发送消息", "Aucun argent, dépôt ou message ne quitte cette démo"),
  legalPoint: tr("Legal content is a sample rulebook, not advice", "El contenido legal es un reglamento de muestra, no asesoría", "Li aju ci yoon ab misaalu sàrti demo la, du ndigal", "المحتوى القانوني كتيب قواعد تجريبي وليس نصيحة", "আইনি বিষয়বস্তু একটি নমুনা নিয়মপুস্তক, পরামর্শ নয়", "法律内容仅为规则样本，不是建议", "Le contenu juridique est un exemple de règles, pas un conseil"),
  aiProcessingDisclosure: tr("Demo audio and images are uploaded to the configured Base44 AI for processing.", "El audio y las imágenes de demo se suben a la IA configurada de Base44 para procesarlos.", "Baat ak nataalu demo yi dañuy yebal ci AI Base44 bi ñu tëral ngir mu saytu leen.", "يتم تحميل صوت وصور العرض إلى ذكاء Base44 الاصطناعي المُعد للمعالجة.", "ডেমো অডিও ও ছবি প্রক্রিয়াকরণের জন্য কনফিগার করা Base44 AI-তে আপলোড হয়।", "演示音频和图片会上传到已配置的 Base44 AI 进行处理。", "L’audio et les images de démonstration sont téléversés vers l’IA Base44 configurée pour traitement."),
  continue: tr("Continue with fictional Rosa", "Continuar con Rosa ficticia", "Wéyal ak Rosa mi ñu sos", "المتابعة مع روزا الخيالية", "কাল্পনিক রোসার সঙ্গে চালিয়ে যান", "继续使用虚构角色 Rosa", "Continuer avec Rosa, personnage fictif"),
};
